max_epochs: 50
warmup_epochs: 10
batch_size: 48
num_workers: 8
learning_rate: 1e-3
weight_decay: 1e-3
# num_devices: 8
accumulate_grad_batches: 2
####################################
main_data_storage: /data1/zliang
raw_data_folder_name: Histo_ST_raw
project_data_folder_name: BIG_600K
working_codespace: /home/zliang/BRIDGE_BIG_600K
gene_csv_name: all_intersection_genes_number_7730.csv
generation_date: "20240601"
####################################
image_encoder_model_name: DenseNet121
freeze_image_encoder_parameter: False
# gene_encoder_model_name: TabNet
freeze_gene_encoder_parameter: False
####################################
input_gene_number: 7730
number_of_eval_HEG_genes: 100
number_of_eval_HVG_genes: 100
output_gene_dimension: 512 # 1024
latent_embedding_dimension: 128
####################################
contrastive_loss_weight: 1.
masked_contrastive_loss_weight: 1.
image_to_gene_generative_loss_weight: 0.01
gene_reconstruction_loss_weight: 0.01
image_self_supervised_loss_weight: 1.
gene_self_supervised_loss_weight: 1.
####################################
use_normed_patch: True
use_hard_or_soft_contrastive_loss: hard
####################################
TabNet_gene_mask_ratio: 0.25
scGPT_gene_mask_ratio: 0.25
temperature: 0.7